-- MySQL Script generated by MySQL Workbench
-- Sun Dec  9 13:08:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test` ;

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`postagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`postagem` ;

CREATE TABLE IF NOT EXISTS `test`.`postagem` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `text_post` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_post`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`cometarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`cometarios` ;

CREATE TABLE IF NOT EXISTS `test`.`cometarios` (
  `id_cometarios` INT NOT NULL AUTO_INCREMENT,
  `postagem_id_post` INT NOT NULL,
  `text_comentario` VARCHAR(150) NULL,
  PRIMARY KEY (`id_cometarios`),
  CONSTRAINT `fk_cometarios_postagem`
    FOREIGN KEY (`postagem_id_post`)
    REFERENCES `test`.`postagem` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CREATE INDEX `fk_cometarios_postagem_idx` ON `test`.`cometarios` (`postagem_id_post` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
